# Generated by Django 3.1.1 on 2021-09-19 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_tracing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateTimeField(auto_now=True, null=True)),
                ('employee_student_number', models.IntegerField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=200, null=True)),
                ('destination', models.CharField(blank=True, max_length=200, null=True)),
                ('ticket_number', models.IntegerField(blank=True, null=True)),
                ('shuttle_number', models.CharField(blank=True, max_length=200, null=True)),
                ('drivers_name', models.CharField(blank=True, max_length=200, null=True)),
                ('trip_distance', models.IntegerField(blank=True, null=True)),
                ('feedback', models.CharField(blank=True, max_length=200, null=True)),
                ('trip_rating', models.IntegerField(blank=True, null=True)),
                ('fever', models.CharField(blank=True, max_length=200, null=True)),
                ('cold', models.CharField(blank=True, max_length=200, null=True)),
                ('body_pain', models.CharField(blank=True, max_length=200, null=True)),
                ('loss_of_smell', models.CharField(blank=True, max_length=200, null=True)),
                ('loss_of_taste', models.CharField(blank=True, max_length=200, null=True)),
                ('headache', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
