# Generated by Django 3.1.1 on 2021-09-19 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0002_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_tracing',
            name='body_pain',
        ),
        migrations.RemoveField(
            model_name='contact_tracing',
            name='cold',
        ),
        migrations.RemoveField(
            model_name='contact_tracing',
            name='headache',
        ),
        migrations.RemoveField(
            model_name='contact_tracing',
            name='loss_of_smell',
        ),
        migrations.RemoveField(
            model_name='contact_tracing',
            name='loss_of_taste',
        ),
        migrations.AlterField(
            model_name='contact_tracing',
            name='fever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracing.choices'),
        ),
    ]
