# Generated by Django 3.1.1 on 2021-09-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0004_auto_20210919_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='cold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cold', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fever', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
