# Generated by Django 3.1.1 on 2021-09-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0005_cold_fever'),
    ]

    operations = [
        migrations.CreateModel(
            name='body_pain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_pain', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
