# Generated by Django 3.1.1 on 2021-09-21 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0006_body_pain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_tracing',
            name='fever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracing.fever'),
        ),
    ]
