# Generated by Django 3.1.1 on 2021-09-21 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0007_auto_20210921_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_tracing',
            name='body_pain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracing.body_pain'),
        ),
        migrations.AlterField(
            model_name='contact_tracing',
            name='cold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracing.cold'),
        ),
    ]
