# Generated by Django 3.1.1 on 2021-09-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0008_auto_20210921_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='loss_of_smell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss_of_smell', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
