# Generated by Django 3.1.1 on 2021-09-21 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0009_loss_of_smell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_tracing',
            name='loss_of_smell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracing.loss_of_smell'),
        ),
    ]
