# Generated by Django 3.1.1 on 2021-09-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0010_auto_20210921_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='headache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headache', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='loss_of_taste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss_of_taste', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
