# Generated by Django 4.0.3 on 2022-11-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
