# Generated by Django 3.2.16 on 2022-11-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_author_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='student_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='year_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
