# Generated by Django 3.2.16 on 2022-11-09 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20221109_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='student_number',
            new_name='student_or_employee_number',
        ),
    ]
