# Generated by Django 3.2.16 on 2022-11-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_author_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='course',
            new_name='course_or_department',
        ),
    ]
