# Generated by Django 3.2.16 on 2022-11-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_author_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('sex_id', models.AutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
