# Generated by Django 3.2.16 on 2022-11-17 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.sex'),
        ),
    ]
