# Generated by Django 3.2.16 on 2022-11-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_author_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='has_role',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
