# Generated by Django 3.1.1 on 2021-10-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20211022_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='date_filed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
