# Generated by Django 3.1.1 on 2021-11-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20211022_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='easy_maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
