# Generated by Django 3.1.1 on 2021-11-29 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_easy_maps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='easy_maps',
        ),
    ]
