# Generated by Django 3.1.1 on 2021-11-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_delete_easy_maps'),
    ]

    operations = [
        migrations.CreateModel(
            name='easy_maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
