# Generated by Django 3.1.1 on 2021-11-29 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_stations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stations',
            name='driver',
        ),
    ]
