# Generated by Django 3.1.1 on 2021-11-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_auto_20211129_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stations',
            name='driver',
        ),
        migrations.AddField(
            model_name='shuttle',
            name='driver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
