# Generated by Django 3.1.1 on 2021-12-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_auto_20211129_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stations',
            old_name='longlat',
            new_name='lat',
        ),
        migrations.AddField(
            model_name='stations',
            name='lon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
