# Generated by Django 3.1.1 on 2021-12-09 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_imhere'),
    ]

    operations = [
        migrations.CreateModel(
            name='tracing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.DateTimeField(auto_now_add=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.stations')),
            ],
        ),
    ]
