# Generated by Django 3.1.1 on 2021-12-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0020_tracing_hdf_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
