# Generated by Django 3.1.1 on 2021-12-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0022_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='answers',
        ),
    ]
