# Generated by Django 3.1.1 on 2021-12-09 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0024_hdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdf',
            name='a2',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a2', to='ticket.answers'),
        ),
        migrations.AddField(
            model_name='hdf',
            name='a3',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a3', to='ticket.answers'),
        ),
        migrations.AddField(
            model_name='hdf',
            name='a4',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a4', to='ticket.answers'),
        ),
        migrations.AddField(
            model_name='hdf',
            name='a5',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a5', to='ticket.answers'),
        ),
        migrations.AddField(
            model_name='hdf',
            name='q2',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q2', to='ticket.questions'),
        ),
        migrations.AddField(
            model_name='hdf',
            name='q3',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q3', to='ticket.questions'),
        ),
        migrations.AddField(
            model_name='hdf',
            name='q4',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q4', to='ticket.questions'),
        ),
        migrations.AddField(
            model_name='hdf',
            name='q5',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q5', to='ticket.questions'),
        ),
    ]
