# Generated by Django 3.1.1 on 2021-12-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0028_tickets_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
