# Generated by Django 4.0.3 on 2022-04-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0029_tickets_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
