# Generated by Django 3.1.1 on 2022-10-06 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0030_tickets_cancel_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserve',
            fields=[
                ('reserve_id', models.AutoField(primary_key=True, serialize=False)),
                ('reserve_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
