# Generated by Django 4.0.3 on 2022-10-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0031_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_status',
            fields=[
                ('ticket_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='status',
        ),
        migrations.AddField(
            model_name='tickets',
            name='ticket_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
