# Generated by Django 4.0.3 on 2022-10-26 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0033_alter_tickets_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='reason',
        ),
    ]
