# Generated by Django 4.0.3 on 2022-10-26 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0034_remove_tickets_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='participants',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.tickets')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
