# Generated by Django 4.0.3 on 2022-10-26 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0035_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='user',
            new_name='participant_user',
        ),
    ]
