# Generated by Django 4.0.3 on 2022-11-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0036_rename_user_participants_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='hdf',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
