# Generated by Django 3.2.16 on 2022-11-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0038_remove_hdf_email_hdf_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdf',
            name='a1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hdf',
            name='a2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hdf',
            name='a3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hdf',
            name='a4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hdf',
            name='a5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
