# Generated by Django 3.2.16 on 2022-11-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0039_auto_20221107_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hdf',
            name='a4',
        ),
        migrations.RemoveField(
            model_name='hdf',
            name='a5',
        ),
        migrations.RemoveField(
            model_name='hdf',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='hdf',
            name='q5',
        ),
    ]
