# Generated by Django 3.2.16 on 2022-11-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0041_hdf_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='shuttle_service',
            fields=[
                ('shuttle_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('plate_number', models.CharField(blank=True, max_length=255, null=True)),
                ('driver', models.CharField(blank=True, max_length=255, null=True)),
                ('shuttle_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
