# Generated by Django 3.2.16 on 2022-11-09 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0042_shuttle_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shuttle_service',
            old_name='shuttle_url',
            new_name='gps_link',
        ),
    ]
