# Generated by Django 3.2.16 on 2022-11-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0045_rename_driver_shuttle_service_driver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
