# Generated by Django 3.2.16 on 2022-11-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0046_participants_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='driver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
