# Generated by Django 3.2.16 on 2022-11-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0047_auto_20221111_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
