# Generated by Django 3.2.16 on 2022-11-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0048_tickets_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='shuttle_driver',
            fields=[
                ('shuttle_driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shuttle_service_list',
            fields=[
                ('shuttle_service_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('shuttle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('plate_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
