# Generated by Django 3.2.16 on 2022-11-15 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0051_auto_20221114_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='shuttle_ride',
            fields=[
                ('shuttle_ride_id', models.AutoField(primary_key=True, serialize=False)),
                ('shuttle_ride_date', models.DateTimeField(auto_now_add=True)),
                ('shuttle_ride_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.shuttle_service_list')),
            ],
        ),
    ]
