# Generated by Django 3.2.16 on 2022-11-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0052_shuttle_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttle_ride',
            name='shuttle_ride_log',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
