# Generated by Django 3.2.16 on 2022-11-17 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_author_image'),
        ('ticket', '0053_alter_shuttle_ride_shuttle_ride_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttle_ride',
            name='shuttle_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.author'),
        ),
    ]
