# Generated by Django 3.2.16 on 2022-12-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0055_alter_tickets_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shuttle_ride',
            name='shuttle_user',
        ),
        migrations.AddField(
            model_name='shuttle_ride',
            name='shuttle_service_id',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
