# Generated by Django 3.2.16 on 2022-12-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0056_auto_20221220_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttle_ride',
            name='shuttle_service_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
